### ISSUE TITLE
Allow kojak to serve report as an HTML report served by flask/gunicorn by example

### ISSUE THREAD

**Issue by 4383** [4383/kojak#6]
Allow kojak to serve report as an HTML report served by flask/gunicorn by example

**Comment by hobbestigrou** [comment]
Why you talk about flask and gunicorn? For me is not necessary a simple static page report is sufficient.

**Comment by 4383** [comment]
yeah we already discuss about this offline I agreed static is enough.

**Comment by hobbestigrou** [comment]
I close this ticket that will be fixed by #22 with jinja.
